#!/usr/bin/env python

import sys

from rqt_quad.quad import Quad
from rqt_gui.main import Main

plugin = 'rqt_quad'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin)) # , plugin_argument_provider=Svo.add_arguments