#!/usr/bin/env python

import sys

from dvs_calibration_gui.calib import Calib
from rqt_gui.main import Main

plugin = 'dvs_calibration_gui'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
